common: remove "ca" option handling
With Koji 1.24, koji-ansible crashed when setting up a session because
it tried to process the "ca" profile option that no longer exists:

AttributeError: 'Values' object has no attribute 'ca'

Since the "ca" option essentially had no effect, just remove support for
it entirely. As described at https://pagure.io/koji/issue/2182, the
correct solution for users is to remove the "ca" setting from their Koji
profile configurations.